version: '3.8'

services:
  test:
    build: 
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://mongo-test:27017/testdb
    depends_on:
      - mongo-test
    networks:
      - test-network

  mongo-test:
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge